version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017-27019:27017-27019'
    command: mongod
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo-data:/data/db
    networks:
      - lib_api

  back-end:
    container_name: back-end
    build:
      context: ./packages/back-end
      dockerfile: BE.Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - WAIT_HOSTS=mongodb:27017
      - NODE_ENV=production
    ports:
      - 3030:8080
    volumes:
      - ./packages/back-end:/usr/src
    networks:
      - lib_api

networks:
  lib_api:
    driver: bridge
