version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo-data:/data/db
    networks:
      - lib_api

  back-end:
    container_name: back-end
    build:
      context: ./packages/back-end
      dockerfile: BE.Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - WAIT_HOSTS=mongodb:27017
      - NODE_ENV=production
    networks:
      - lib_api
    depends_on:
      - mongo

  front-end:
    container_name: front-end
    build:
      context: ./packages/front-end
      dockerfile: FE.Dockerfile
    networks:
      - nginx_server
    depends_on:
      - back-end

  nginx:
    container_name: nginx
    build:
      context: ./packages/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    networks:
      - nginx_server
    depends_on:
      - front-end

networks:
  nginx_server:
    driver: bridge
  lib_api:
    driver: bridge
